spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aloha
    username: root
    password: your_password
    driverClassName: com.mysql.jdbc.Driver
  tomcat:
          uri-encoding: UTF-8